# Generated by Django 4.1.2 on 2022-10-28 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='Fecha de la orden')),
                ('pickup_place', models.JSONField(verbose_name='Lugar de recogida')),
                ('destination_place', models.JSONField(verbose_name='Lugar de destino')),
                ('order_status', models.BooleanField(default=False, verbose_name='Estado de finalización de la ordeb')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_to_driver', to='driver.driver', verbose_name='Conductor')),
            ],
        ),
    ]
