# Generated by Django 4.1.2 on 2022-10-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_order_date',
            field=models.DateTimeField(default='2022-10-28', verbose_name='Fecha fin de la orden'),
            preserve_default=False,
        ),
    ]
