# Generated by Django 4.1.2 on 2022-10-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_end_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_order_date',
            field=models.DateTimeField(verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=False, verbose_name='Estado de finalización de la orden'),
        ),
    ]
