# Generated by Django 4.1.2 on 2022-10-28 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre del Conductor')),
                ('last_name', models.CharField(max_length=25, verbose_name='Apellido del Conductor')),
                ('nuip', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Número de identificación')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_to_vehicule', to='vehicles.vehicle', verbose_name='vehiculo del conductor')),
            ],
        ),
    ]
