# Generated by Django 4.1.2 on 2022-10-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default=1, max_length=8, verbose_name='Placa del Vehiculo'),
            preserve_default=False,
        ),
    ]
